"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# S4: env-driven, dev-safe defaults. Local dev / Docker keep working with no env
# vars set; production overrides via the environment (see deployment checklist).

def _env_bool(name, default):
    val = os.environ.get(name)
    if val is None:
        return default
    return val.strip().lower() in ("1", "true", "yes", "on")


# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to the insecure dev key only when SECRET_KEY isn't set. Set
# SECRET_KEY in the environment for any non-local deployment.
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-ye)u(c7ku67fctb*mgycyhuj8#m$-#hmw4&w02th$4az&!051_",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True for dev; set DEBUG=0 (or false/no/off) in prod.
DEBUG = _env_bool("DEBUG", True)

# Comma-separated host list from ALLOWED_HOSTS env; defaults keep localhost and
# the LAN IP working for local play. e.g. ALLOWED_HOSTS="example.com,1.2.3.4"
_default_hosts = "192.168.1.22,localhost,127.0.0.1"
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("ALLOWED_HOSTS", _default_hosts).split(",")
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    "daphne",
    "game",
    # S4: let WhiteNoise (not Django's dev static handler) serve static under
    # runserver too, so dev and prod take the same code path. Must precede
    # django.contrib.staticfiles.
    "whitenoise.runserver_nostatic",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
]

ASGI_APPLICATION = "server.asgi.application"

# Channel layer.
#
# Docker / prod set REDIS_URL (e.g. redis://redis:6379/0) and use Redis so the
# layer works across multiple worker processes. Local dev sets neither and falls
# back to the in-process in-memory layer, so a single `manage.py runserver`
# works out of the box with no Redis and no channels_redis dependency.
#
# (Previously this was hardcoded to host "redis", which doesn't resolve outside
# Docker — so every websocket connect dropped with "Connection lost" locally.)
REDIS_URL = os.environ.get("REDIS_URL")
REDIS_HOST = os.environ.get("REDIS_HOST")
if REDIS_URL or REDIS_HOST:
    _hosts = [REDIS_URL] if REDIS_URL else [
        (REDIS_HOST, int(os.environ.get("REDIS_PORT", "6379")))
    ]
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": _hosts},
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"},
    }

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # S4: WhiteNoise serves static files directly (must sit right after
    # SecurityMiddleware). It serves STATIC_ROOT under runserver too, so the
    # no-cache gap (NoCacheStaticMiddleware didn't fire for runserver's static
    # handler) is closed and the same path works after `collectstatic` in prod.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "game.middleware.NoCacheStaticMiddleware",  # DEBUG: stop browsers caching stale JS modules
]

ROOT_URLCONF = "server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "server.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# S4: WhiteNoise static serving.
# - STATIC_ROOT is where `collectstatic` writes for prod; WhiteNoise serves it.
# - In DEBUG we use the finders so WhiteNoise serves straight from
#   STATICFILES_DIRS with no collectstatic step (dev stays zero-config), and we
#   disable max-age caching so stale ES modules never get cached.
# - In prod, CompressedManifestStaticFilesStorage hashes + gzips/brotlis assets
#   (run `collectstatic` first); WhiteNoise then serves them with far-future
#   cache headers safely (filenames are content-hashed).
STATIC_ROOT = BASE_DIR / "staticfiles"
WHITENOISE_USE_FINDERS = DEBUG
WHITENOISE_AUTOREFRESH = DEBUG
if DEBUG:
    WHITENOISE_MAX_AGE = 0

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if not DEBUG
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

# Matches the BigAutoField that migration 0010 set for GameAction, so the
# auto-PK isn't re-detected as a model change on every makemigrations.
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
