# Generated by Django 5.2.10 on 2026-02-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='num_players',
            field=models.IntegerField(default=4),
        ),
    ]
