# Generated by Django 5.2.11 on 2026-02-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_num_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='phase',
            field=models.CharField(default='DEALING', max_length=20),
        ),
    ]
