# Generated by Django 5.2.11 on 2026-02-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn_step',
            field=models.CharField(default='PICK', max_length=20),
        ),
    ]
