# Generated by Django 5.2.11 on 2026-02-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_player_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_type',
            field=models.CharField(choices=[('HUMAN', 'Human'), ('AI', 'AI')], default='HUMAN', max_length=10),
        ),
    ]
