# Generated by Django 5.2.11 on 2026-04-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_gameaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='maal_card',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='shown_sequences',
            field=models.JSONField(default=list),
        ),
    ]
