# Generated by Django 5.2.11 on 2026-04-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_maal_card_player_shown_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='turn_count',
            field=models.IntegerField(default=0),
        ),
    ]
