# Generated by Django 6.0.1 on 2026-06-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_player_turn_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="code",
            field=models.CharField(
                blank=True, db_index=True, max_length=12, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="is_joined",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="gameaction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
