# Generated by Django 5.2.15 on 2026-06-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_game_code_player_is_joined_alter_gameaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_owner',
            field=models.BooleanField(default=False),
        ),
    ]
