# Generated by Django 5.2.15 on 2026-06-25 04:40

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_player_has_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.IntegerField(default=game.models.random_avatar),
        ),
    ]
