# Generated by Django 6.0.1 on 2026-06-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0012_player_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="turn_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
