# Generated by Django 6.0.1 on 2026-06-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0012_player_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="round_number",
            field=models.IntegerField(default=1),
        ),
    ]
