# Generated by Django 6.0.1 on 2026-06-25 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0013_game_round_number"),
        ("game", "0013_game_turn_deadline"),
    ]

    operations = []
