# Generated by Django 6.0.1 on 2026-06-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0014_merge_0013_game_round_number_0013_game_turn_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="allow_peek",
            field=models.BooleanField(default=False),
        ),
    ]
